GET_USER_COURSES_QUERY = """query getUserCourses($id: ID!, $type: ENTITY_TYPE_ENUM!, $filters: CourseFilter, $isCurriculumProgramFree: Boolean! = false, $courseGradeFilters: CourseGradeFilters, $enabledModulesFilters: EnabledModulesFiltersInput) { node(id: $id, type: $type) { id ... on Student { id courses(orderBy: TITLE, orderByDirection: ASC, filters: $filters) { id title __typename } __typename } __typename } }"""

GET_STUDENT_TASKS_QUERY = """query getStudentTasks($userId: ID!, $studentIds: [ID!], $filters: TaskFilter, $first: Int, $after: String, $orderByDirection: ORDER_BY_DIRECTION, $type: ENTITY_TYPE_ENUM!) { node(id: $userId, type: $type) { id ... on Student { id tasks(filters: $filters, first: $first, after: $after, orderByDirection: $orderByDirection) { pageInfo { hasNextPage hasPreviousPage startCursor endCursor __typename } totalCount edges { id orderDate itemType item { id ... on StudentAssignment { id status isSubmitted isEvaluated state conversation { id unreadMessageCount __typename } submission { id status statusV2 __typename } assignment { id label contentType isFixedStartTime isStudentSubmissionEnabled isTeacherEvaluationEnabled deadline closeSubmissionDate visibility state { state publishedAt __typename } course { id title __typename } content { ... on Assessment { id assessmentType { id value __typename } title { id value __typename } image { id value __typename } __typename } ... on AssignmentResource { id label __typename } __typename } __typename } lockingState { state __typename } isEvaluationApplicable __typename } __typename } __typename } __typename } __typename } }"""

GET_ASSIGNMENT_DETAILS_QUERY = """query getAssignmentDetails($id: ID!, $studentIds: [ID!], $showOnlySubmitted: Boolean, $userFilter: TOOL_RESPONSE_USER_FILTER_ENUM, $unreadMessageCountFilters: UnreadMessageCountFilters, $entityEventsFilter: EntityEventsFilter, $organizationResourcesOrderBy: ORDER_BY_ENUM, $organizationResourcesOrderByDirection: ORDER_BY_DIRECTION, $organizationResourcesFirst: Int, $organizationResourceFilters: OrganizationResourceFilter, $userArchivedFilters: UserArchivedFilters, $fetchAiUsageMetrics: Boolean = false) { node(id: $id, type: ASSIGNMENT) { id ... on Assignment { id contentType publishedAt state { state publishedAt __typename } content { id ... on Assessment { title { id value __typename } allFields { id uid value __typename } organizationResources: organizationResourcesV2(orderBy: $organizationResourcesOrderBy, orderByDirection: $organizationResourcesOrderByDirection, first: $organizationResourcesFirst, filters: $organizationResourceFilters) { edges { node { id label attachment { id type signedUrl name __typename } __typename } __typename } __typename } __typename } ... on AssignmentResource { id label title attachments { id name type signedUrl __typename } __typename } __typename } deadline closeSubmissionDate visibility classDiscussion { id unreadMessageCount __typename } assignedStudents(studentIds: $studentIds) { id isSubmitted evaluatedAt studentResponsePostStatus student { id firstName lastName type __typename } submission(showOnlySubmitted: $showOnlySubmitted) { id status statusV2 submittedAt returnedAt isDraftSubmission __typename } __typename } counts { totalAssignedStudents totalSubmissions totalDraftSubmissions __typename } course { id grade { id __typename } subjects { id name type __typename } primaryGrade { id name __typename } __typename } createdBy { id firstName lastName __typename } __typename } __typename } }"""

GET_STUDENT_ASSIGNMENT_QUERY = """query getStudentAssignment($id: ID!, $userFilter: TOOL_RESPONSE_USER_FILTER_ENUM, $entityEventsFilter: EntityEventsFilter, $userArchivedFilters: UserArchivedFilters) { node(id: $id, type: STUDENT_ASSIGNMENT) { id ... on StudentAssignment { id state status isSubmitted isEvaluationApplicable student { id firstName lastName email type __typename } submissions { edges { id attachmentGroups { id attachments { id name type mimeType url signedUrl __typename } __typename } attachments { id name type mimeType url signedUrl __typename } status statusV2 submittedAt returnedAt isDraftSubmission __typename } __typename } assignment { id isSimilarityCheckEnabled showStudentResponse course { id primaryGrade { id name __typename } subjects { id name type __typename } __typename } curriculumProgram { id type __typename } closeSubmissionDate content { id __typename } __typename } conversation { id unreadMessageCount __typename } aiEvaluationJob(filters: {isFetchLatestJob: true}) { id status metadata __typename } post { id publishedAt state __typename } __typename } __typename } }"""

GET_BEHAVIOUR_INCIDENTS_QUERY = """query getBehaviourIncidentFeed($id: ID!, $input: BehaviourIncidentFeedInput, $accessibleUsersInput: BehaviourAccessibleUsersInput!, $includeAccessibleUsers: Boolean = false) { node(id: $id, type: ORGANIZATION) { ... on Organization { id behaviourIncidentFeed(input: $input) { totalCount edges { node { id uid title category { id name color level rootCategory { id name sentiment { id label __typename } __typename } __typename } severity { id level name color __typename } createdAt createdBy { id firstName middleName lastName __typename } __typename } __typename } __typename } __typename } __typename } }"""

GET_ATTENDANCE_PERCENTAGES_QUERY = """query getStudentAttendanceStatisticsV2($studentId: ID!, $filters: StudentAttendanceFilters, $overAllPresenceFilter: StudentAttendanceFilters) { node(id: $studentId, type: STUDENT) { id ... on Student { id overallPresence: attendanceV2(filters: $overAllPresenceFilter) { presenceOverview { totalCount presencePercentage absencePercentage presenceNumber absenceNumber __typename } __typename } attendanceV2(filters: $filters) { categorySummary { percentageItems { category { id label color __typename } percentage __typename } __typename } __typename } __typename } __typename } }"""
